name: GitlabSync
run-name: ${{ github.actor }} is testing out sync ðŸš€
on:
  - push
jobs:
  sync:
    runs-on: ubuntu-latest
    name: Git Repo Sync 
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: reijiokito/sync@main
      with:
        target-url: git@repo.gviet.vn:sigma-livestream/sigma-machine/sync.git
        target-username: congnt@gviet.vn
        target-token: rYH_i9oN6fj7v2FxyoSX
